#!/bin/sh
alias j='z'
alias f='zi'
alias g='lazygit'

# Get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize grep output
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# Confirm before overwriting something
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"

# Easier to read disk
alias df="df -h"	# human-readable sizes
alias free="free -m"	# show sizes in MB

# Get top processes eating memory
alias psmem="ps auxf | sort -nr -k4 | head -5"

# Get top processes eating CPU
alias pscpu="ps auxf | sort -nr -k 3 | head -5"

# Colorize ls
alias ls="ls --color=auto"
alias ll="ls -l --color=auto"
alias la="ls -la --color=auto"

# Update/sync google drive
alias gdrive-update="/opt/backup.sh"

# Manage dotfiles
alias dotfiles='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
